### ISSUE TITLE
There are a couple new sizes for the watch, any plan to add them?

### ISSUE THREAD

**Issue by oxcug** [ali-zahedi/appicon#1]
Awesome pylib, actually just saved me a ton of work!

Looks like with Xcode (13?) they added some new Watch sizes:

* 66x66 @2x (Apple Watch Notification Center)
* 92x92 @2x (Apple Watch Home Screen)
* 102x102 @2x (Apple Watch Home Screen)
* 234x234 @2x (Apple Watch Short Look)

Any plans to add these sizes? Also happy to make a PR.

**Comment by ali-zahedi** [comment]
@oxcug Sounds good, if you can make a PR. I'll be waiting for it.

**Comment by ali-zahedi** [comment]
@oxcug Do you have any chance?

For iOS you should put this size in [`Contents.json`](https://github.com/ali-zahedi/appicon/blob/master/appicon/ios/Contents.json)
also for Android you can find [`Contents.json` here](https://github.com/ali-zahedi/appicon/blob/master/appicon/android/Contents.json)

**Comment by oxcug** [comment]
@ali-zahedi Just updated the contents.json. Created a new branch for PR, but looks like I need write permissions for the repo? Here's the file for ref:

[Contents.txt](https://github.com/ali-zahedi/appicon/files/7584051/Contents.txt)


Also updated some of the other file names to be more consistent.

**Comment by ali-zahedi** [comment]
@oxcug Thanks.
you should fork first. then switch on develop branch, fix, commit, push(on your fork) then you can make a PR. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by oxcug** [comment]
Done and done, opened up #2 .
